ll_project/accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

ll_project/learning_log/urls.py
# learning_log urls
from django.urls import path
from . import views

app_name = 'learning_log'

urlpatterns = [
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    path('topic/<int:topic_id>/', views.topic, name='topic'),
    path('new_topic/', views.new_topic, name='new_topic'),
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry')
]

ll_project/ll_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_log.urls')),
    path('accounts/', include('accounts.urls')),
]

ll_project/accounts/models.py
from django.db import models

# Create your models here.

ll_project/learning_log/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
    text = models.CharField(max_length=200)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)
    
    # string representation of a topic
    def __str__(self):
        if len(self.text) > 50:
            return f'{self.text[:50]}...'
        else:
            return self.text

class Entry(models.Model):
    # The entries model
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural = 'entries'
    
    # The string representation of an entry
    def __str__(self):
        if len(self.text) > 50:
            return f'{self.text[:50]}...'
        else:
            return self.text

ll_project/learning_log/forms.py
from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
    

ll_project/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login

def register(request):
    '''Register a new user'''
    if request.method != 'POST':
        # create an empty form
        form = UserCreationForm()
        
    else:
        # process data
        form = UserCreationForm(data=request.POST)
        # validate the data
        if form.is_valid():
            new_user = form.save() # save the new user
            login(request, new_user) # log in to the users account
            return redirect('learning_log:index') # redirect to Homepage
        
    # assemble the needed data into context dictionary
    context = {'form': form}
    # return the context(data) and the html template for registration
    return render(request, 'registration/register.html', context)

ll_project/learning_log/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Topic, Entry
from .forms import TopicForm, EntryForm
from django.http import Http404

def index(request):
    # returns the homepage
    return render(request, 'learning_log/index.html')

@login_required
def topics(request):
    # fetch topics belonging to the user, sorted by date added
    topics = Topic.objects.filter(owner=request.user).order_by('-date_added')
    # assemble the required data
    context = {'topics': topics}
    # return data and topics template
    return render(request, 'learning_log/topics.html', context)

@login_required
def topic(request, topic_id):
    # fetch topic and all its entries
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    # raise error if user isn't the owner
    if request.user != topic.owner:
        raise Http404
    
    # Assemble the data required and return it with the topic template
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_log/topic.html', context)

@login_required
def new_topic(request):
    # adding a new topic
    if request.method != 'POST':
        # create a new empty form
        form = TopicForm()
    else:
        # process the data
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new = form.save(commit=False)
            new.owner = request.user
            new.save()
            return redirect('learning_log:topics')
    
    # assemble data and return it with template
    context = {'form': form}
    return render(request, 'learning_log/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    # raise error if user isn't the owner
    if request.user != topic.owner:
        raise Http404
    
    if request.method != 'POST':
        # new blank form
        form = EntryForm()
    else:
        # process the data
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new = form.save(commit=False)
            new.topic = topic
            new.save()
            return redirect('learning_log:topic', topic_id=topic.id)
    
    # assemble data and return 
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_log/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    # edit an entry
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    
    # raise error if user isn't owner
    if request.user != topic.owner:
        raise Http404
    
    if request.method != 'POST':
        # prefill form with current data
        form = EntryForm(instance=entry)
    else:
        # process data
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_log:topic', topic_id=topic.id)
        
    # assemble data and return data + template
    context = {'form': form, 'entry': entry, 'topic': topic}
    return render(request, 'learning_log/edit_entry.html', context)

ll_project/learning_log/templates/learning_log/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title> {% block title %}{% endblock %} </title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'learning_log/css/base_styles.css' %}">
        {% block extra_head %}{% endblock extra_head %}
    </head>
    <body>
        <div class="nav-bar">
            <p>
                <div id="nav">
                    <a href="{% url 'learning_log:index' %}">Home</a>
                </div>
                <div id="nav">
                    <a href="{% url 'learning_log:topics' %}">Topics</a>
                </div>

            {% if user.is_authenticated %}
                <div id="nav">
                    <form action="{% url 'accounts:logout' %}" method="post">
                        {% csrf_token %}
                        <button name="submit" id="logout-button">Sign out</button>
                    </form>
                </div>
                <div id="nav">Hello {{ user.username }}</div>
            {% else %}
                <div id="nav"><a href="{% url 'accounts:login' %}">Login</a></div>
                <div id="nav"><a href="{% url 'accounts:register' %}">Register</a></div>
            {% endif %}
            </p>
        </div>
        <div id="content">
        {% block content %}
            
        {% endblock content %}
        </div>
        <hr>
        <div class="footer">
            <p>
                <b><i style="font-size:0.9em;">&copy; 2025 Learning Logs App</i></b>
            </p>
        </div>
        
    </body>
</html>

ll_project/learning_log/templates/learning_log/edit_entry.html
{% extends 'learning_log/base.html' %}

{% block title %}Edit Entry{% endblock title %}

{% block content %}
<h1>Edit Entry</h1>
<p>
    <b>Topic :</b>
    <a href="{% url 'learning_log:topic' topic.id %}">
        <i>{{ topic.text }}</i>
    </a>
</p>
<p>Edit entry:</p>
<form action="{% url 'learning_log:edit_entry' entry.id %}" method="post" id="large-form">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit" id="form-button">Save</button>
</form>

{% endblock content %}

ll_project/learning_log/templates/learning_log/index.html
{% extends 'learning_log/base.html' %}

{% block title %}Homepage{% endblock %}

{% block content %}
<h1>Welcome to Your Learning Logs!</h1>

<p>Your personal space to track, organize, and reflect on everything you're learning. Whether it's a new programming language, a historical period, a musical instrument, or simply daily observations, Learning Logs helps you keep it all in one place.</p>
<p>
  <strong>With Learning Logs, you can:</strong>
</p>
<ul>
  <li>Create personalized topics for any subject.</li>
  <li>Add detailed entries to document your progress, insights, and questions.</li>
  <li>Easily review and revisit your learning journey.</li>
</ul>

{% if user.is_authenticated %}
    <p>
        Want to view your topics? 
        <a href="{% url 'learning_log:topics' %}">click here.</a>
    </p>
{% else %}
    <div>
        <p>
            Ready to start logging your knowledge?
            <a href="{% url 'accounts:register' %}">Register Now</a>
        </p>
        <p>Already have an account? <a href="{% url 'accounts:login' %}">Log In</a></p>
    </div>
{% endif %}

<div class="features">
  <h2>Why Learning Logs?</h2>
  <p>In today's fast-paced world, continuous learning is key. But how often do we truly retain what we learn? Learning Logs provides a structured yet flexible way to solidify your understanding and see your growth over time. It's more than just a notebook; it's a dynamic record of your intellectual development.</p>
  <ul>
    <li><strong>Organized:</strong> Keep all your learning notes neatly categorized by topic.</li>
    <li><strong>Reflective:</strong> Encourage deeper understanding by prompting you to summarize and reflect.</li>
    <li><strong>Accessible:</strong> Access your logs anytime, anywhere.</li>
    <li><strong>Motivating:</strong> See your progress and stay inspired on your learning journey.</li>
  </ul>
</div>

{% endblock content %}

ll_project/learning_log/templates/learning_log/new_entry.html
{% extends 'learning_log/base.html' %}

{% block title %}New Entry{% endblock title %}

{% block content %}
<h1>New Entry</h1>
<p>Add a new entry below.</p>
<p>
    <b>Topic : </b><i> 
        <a href="{% url 'learning_log:topic' topic.id %}">{{ topic.text }}</a>    
    </i>
</p>
<form action="{% url 'learning_log:new_entry' topic.id %}" method="post" id="large-form">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit" id="form-button">Add Entry</button>
</form>

{% endblock content %}

ll_project/learning_log/templates/learning_log/new_topic.html
{% extends 'learning_log/base.html' %}

{% block title %}New Topic{% endblock %}

{% block content %}
<h1>New Topic</h1>
<p>Add a new topic</p>
<form action="{% url 'learning_log:new_topic' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit" id="form-button">Add Topic</button>
</form>

{% endblock content %}

ll_project/learning_log/templates/learning_log/topic.html
{% extends 'learning_log/base.html' %}

{% block title %}{{ topic.text }}{% endblock title %}

{% block content %}
<h1>Entries</h1>
<p><b>Topic</b> : <i>{{ topic.text }}</i>.</p>

<p>
    <a href="{% url 'learning_log:new_entry' topic.id %}">Add a new Entry</a>
</p>
<ul>
    {% for entry in entries %}
        <li>
            <p>
                <b>{{ entry.date_added|date:'M d, Y' }}</b>
                <i>{{ entry.date_added|date:' H:i' }}</i>
            </p>
            
            <p>{{ entry.text|linebreaks }}</p>
            <p>
                <a href="{% url 'learning_log:edit_entry' entry.id %}">Edit Entry</a>
            </p>
        </li>
    {% empty %}
        <li>No entries added for this topic!</li>
    {% endfor %}
</ul>

{% endblock content %}

ll_project/learning_log/templates/learning_log/topics.html
{% extends 'learning_log/base.html' %}

{% block title %}Topics{% endblock title %}

{% block content %}

<h1>Topics</h1>
<p>The following are topics added:</p>

<ul>
{% for topic in topics %}
    <li>
        <a href="{% url 'learning_log:topic' topic.id %}">
            {{ topic.text }}
        </a>
    </li>
{% empty %}
    <li>No Topics are added yet.</li>
{% endfor %}
</ul>

<p>
    <a href="{% url 'learning_log:new_topic' %}">Add a new topic</a>
</p>

{% endblock content %}